CREATE TABLE QGPL.USRRPTPGM (USER_ID CHARACTER (10 ) NOT
NULL WITH DEFAULT, IS_EXP CHARACTER (3 ) NOT NULL WITH DEFAULT,
EXP_DAYS NUMERIC (3 ) NOT NULL WITH DEFAULT, SYS_HOST CHARACTER
(8 ) NOT NULL WITH DEFAULT, TEXT_DESC CHARACTER (50 ) NOT NULL WITH
DEFAULT)
